---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "config-server"
spec:
  selector:
    matchLabels:
      app: "config-server"
  template:
    metadata:
      labels:
        app: "config-server"
    spec:
      containers:
        - name: "config-server-image"
          image: "docker.io/heritier004/ea-project:config-server"
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: "config-server"
spec:
  selector:
    app: "config-server"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "service-discovery"
spec:
  selector:
    matchLabels:
      app: "service-discovery"
  template:
    metadata:
      labels:
        app: "service-discovery"
    spec:
      containers:
        - name: "service-discovery-image"
          image: "docker.io/heritier004/ea-project:service-discovery"
          imagePullPolicy: "Always"
          args: ["--spring.profiles.active=k8s"]
          ports:
            - containerPort: 8761
      initContainers:
        - name: "config-server"
          image: busybox:1.28
          command: [ 'sh', '-c', "until nslookup config-server.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for config-server; sleep 2; done" ]

---
apiVersion: v1
kind: Service
metadata:
  name: "service-discovery"
spec:
  type: NodePort
  selector:
    app: "service-discovery"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8761