version: "3.9"
networks:
  group-1-amdb-project:
    external: true
services:
  users-service:
    container_name: "users-service"
    build: ./users
    ports:
      - "8181:8080"
    image: "docker.io/heritier004/ea-project:users-service"
    command:
      - "--spring.profiles.active=docker"
    networks:
      - "group-1-amdb-project"